apiVersion: v1
description: Installs aether-hub in kubernetes (derived from legacy Beszel chart)
home: https://github.com/henrygd/beszel
name: aether-hub
appVersion: "0.9"
# Do not touch will be updated during release
version: 0.1.0
sources:
  - "Legacy chart: https://github.com/dnikoloski/beszel-kubernetes/tree/main/charts/beszel-hub"
  - "Legacy docs: https://www.beszel.dev/ (Aether site pending)"
  - https://github.com/henrygd/beszel
icon: https://repository-images.githubusercontent.com/825470378/2710c6db-f934-4a8b-a2c4-7a0abbcd2ad6
maintainers:
  - name: dnikoloski
    email: nikoloskid@pm.me
