services:
  aether-agent:
    image: 'loboyanzy/aether-agent'
    container_name: 'aether-agent'
    restart: unless-stopped
    network_mode: host
    # Only when using henrygd/beszel-agent-nvidia
    # runtime: nvidia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.aether:/extra-filesystems/sda1:ro
    environment:
      PORT: 45876
      KEY: '' # set to your SSH public key
      # Only when using henrygd/beszel-agent-nvidia
      # NVIDIA_VISIBLE_DEVICES: all 
      # NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
